### ISSUE TITLE
Rename the repository to "cracko298.github.io"

### ISSUE THREAD

**Issue by Wolfyxon** [Cracko298/cracko298-web#1]
Renaming this repository to "cracko298.github.io" will make the website accessible by just going to https://cracko298.github.io instead of having to go to https://cracko298.github.io/cracko298-web

This would be very convenient.

**Comment by Cracko298** [comment]
I've attempted to rename the repo for a long while.
Never got it too work, I'll look into this.

**Comment by Wolfyxon** [comment]
Wdym? What happens when you try to rename it.

**Comment by Cracko298** [comment]
It gave me some weird build error, I'll be able to confirm when I get home later Sunday

**Comment by Wolfyxon** [comment]
That's weird. Maybe turn off and on the pages feature?

**Comment by Cracko298** [comment]
Changed repo name to "projects", closing this issue.

**Comment by Wolfyxon** [comment]
Make sure to update all the links (in your bio etc.)

**Comment by Cracko298** [comment]
Did so, will be updating other platforms eventually.
